### ISSUE TITLE
HTML in Select Box Unclear

### ISSUE THREAD

**Issue by patcouch** [revsystems/jQuery-SelectBox#13]
I can not find any instructions, I tried copying the function out of the main.js and adding the label, but to no avail. is jquery.tie needed?  Please advice with more accurate instructions.  

PS.  Thanks for your work!  Great Job so far!

**Comment by revsystems** [comment]
Hi,

I'm not sure I understand what problem you're having. I'm assuming you've looked at the attached README.md file?

If you have an example page, I could take a look at that.

Thanks

**Comment by revsystems** [comment]
Closing
