### ISSUE TITLE
a .text not updating with .triggerHandler('reload')

### ISSUE THREAD

**Issue by nicholasdavison** [revsystems/jQuery-SelectBox#14]
I'm running the following code that resets the select box's value. .triggerHandler('reload') correctly updates li.selected but leaves a .text unchanged.

How do I get .text to update as well on .triggerHandler('reload') ?

I inserted the two second delay so I could open the drop down and watch it change.

Same thing happens in both FF3.6 and IE8 on the PC.

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SelectBox Test</title>
<link type="text/css" href="jquery.sb.css" rel="stylesheet" media="all" />
<script type="text/javascript" src="jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="jquery.tie.js"></script>
<script type="text/javascript" src="jquery.sb.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('select').sb({
        useTie: false
    });
    setTimeout(function() {
        $('select').val("Opt1").triggerHandler('reload');
        alert($('select').val());
    }, 2000);
});
</script>
</head>

<body>
    <select>
        <option value="">Please Choose</option>
        <option value="Opt1">Option 1</option>
        <option value="Opt2">Option 2</option>
        <option value="Opt3">Option 3</option>
    </select>
</body>
</html>
```

**Comment by revsystems** [comment]
Hi,

Thanks for the detailed example. A very recent commit moved the initialization of the display outside the load function, so it was being initialized on load, but not reload.

I pushed a new version just now that should fix it. Let me know if that works for ya.

**Comment by nicholasdavison** [comment]
Works beautifully. And thanks for such a fast response. Very cool to see.
