### ISSUE TITLE
Opera: Can't tab to focus

### ISSUE THREAD

**Issue by ghost** [revsystems/jQuery-SelectBox#16]
Normally sb leverages natural tabbing by making the display an &lt;a href='#'^gt;. Opera doesn't recognize this as valid--we may need to actually set a tabindex to make this cross browser compatible.

**Comment by revsystems** [comment]
Tabindexes weren't the answer... Opera actually uses an alternative method for accessibility. It uses CTRL+Up and CTRL+Down to switch between links. This is fine... I made some additional changes to stop the page from scroll on up/down as well.
