### ISSUE TITLE
Not minified version is not working

### ISSUE THREAD

**Issue by pvanderlinden** [revsystems/jQuery-SelectBox#19]
The not minified version isn't working. The original selectbox is still visible, when using the not minified version.

**Comment by revsystems** [comment]
Hi,

I just changed the [demo page](http://dl.dropbox.com/u/124192/websites/selectbox/index.html) to use the minified version as a test, and it seems to work. Could you tell me the error you get (if any) on the page? If it's not working at all, there's a chance that JS is breaking somewhere else on your page.

**Comment by pvanderlinden** [comment]
Hi,

I can't get it reproduced from scratch. In the website I was developing:
- jquery.sb.js: The javascript version was visible, but the select version was also visible, because a style="display:inline-block" was added, can't identify which javascript was causing that
- jquery.sb.min.js: All was working correctly

I've downloaded the minified version and the not minified version several times, and each time this happend. I can look if I can isolate it from the original website, if you are interrested?

**Comment by MaxPower15** [comment]
I think I read your initial comment wrong--you're saying the uncompressed (NOT minified) version is not working.

If you could link me to the original website or a similar environment, I'd be interested in seeing the interactions that are causing the problems.

It's also possible that I somehow messed up pushing the minified version, and it's just an older version that works in your case. Probably this. Anyway, if that's the case, I'd like to see what's wrong so I can fix it.

**Comment by pvanderlinden** [comment]
Ah, I was looking for that word 'uncompressed' ;)

It is a little bit difficult to see what is happening I think, the page is very old: 
http://www.baderie.nl/afspraak-maken/

At the moment, the compressed version is added, which is unminified, so I could add the 'setselected' function. If you replace the 'compressed' version with the uncompressed version, the old selectbox will not disappear.
