### ISSUE TITLE
Selectbox not closing when leaving with tab key

### ISSUE THREAD

**Issue by tvdeyen** [revsystems/jQuery-SelectBox#21]
If I leave a .sb() selectbox with hitting the tab key than the selectbox does not close it self. It stays open.

**Comment by tvdeyen** [comment]
To be more specific:

Leaving to another selectbox works, but not with input fields.

I pasted a demo here:

https://gist.github.com/868991

**Comment by tvdeyen** [comment]
I investigated a little bit more.

You are bluring the selectbox only if you focus another selectbox. Shouldn't the selectbox be blured after it loses focus? (it blures btw ;)

This causes some very strange side effects in my application.

Is there a reason you are doing this. I try to fix this in my fork. But first I have to check you event system. Maybe you have some hints for me.

**Comment by revsystems** [comment]
I know exactly what you're talking about and I had tons of issues fixing it, mostly dealing with performance. I will first try your changes to see if that fixes it.

Thanks

**Comment by revsystems** [comment]
I tried coming up with a fix for this today, but I don't think the way I'm managing blur/focus (utilizing the original `select` elements) allows it to work correctly. Need to think some more on it to see if I can get a clever solution, or if refactoring focus management is needed.

**Comment by revsystems** [comment]
I just pushed a change that I think should fix this. Let me know if it's working for you.

**Comment by revsystems** [comment]
Haven't heard anything, so I'm closing this...

**Comment by tvdeyen** [comment]
Sorry hadn't time to check.

I'll post a new one if I find problems.
