### ISSUE TITLE
Z-Index for IE7

### ISSUE THREAD

**Issue by hcdave** [revsystems/jQuery-SelectBox#24]
Here's hoping people stop using IE7 soon. The options appear behind the boxes in IE7. FWIW here is a little bit of code that fixed the problem. It starts at the top of the .sbHolders and makes each .sbHolder below a lower z-index:

var n = $(".sbHolder").length;

```
$(".sbHolder").each(function() {
 $(this).css("z-index", n);
 n--;
```

**Comment by revsystems** [comment]
The dropdown has a z-index of 99999 by default in the css, and it's appended to the "body" (basically the root element) element unless you've explicitly set the ddCtx option. This should make it always appear on top, even in IE7, unless there's an element on the page with a z-index higher than 99999 (or your page is running in quirks mode... and I am going to ignore that headache, haha).

Does simply changing the z-index in the css fix the issue for you? Would be a bit cleaner than running javascript on it.

If you're sure this isn't working, can you show me an example so I can check it out?

**Comment by hcdave** [comment]
I thought it was just me but I checked this example:

http://www.bulgaria-web-developers.com/projects/javascript/selectbox/

I found it had the same issue. I tried to figure out where to select the ddCtx option but I couldn't find it. Anyway, I agree it would be much better to fix the problem by setting the css it would be MUCH better. I tried changing the z-index on just about every element in the style sheet and nothing worked. 

The code that I wrote seemed to have it working.

I am not sure about the quirks mode. I've got the document set to:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

It's just what is used by default in Dreamweaver. I don't know if that answers any questions. Thank you for replying.

David Krause
432.368.5483
david@cvaadv.com

**Comment by MaxPower15** [comment]
I checked that page, but it doesn't appear to be using my plugin. Similarly named though. Mine is initialized with $("select").sb() while that uses $("select").selectbox().

If you'd like to use mine instead, you can find the files and full documentation here:
https://github.com/revsystems/jQuery-SelectBox

If I'm missing something, let me know.

**Comment by hcdave** [comment]
Thank you. That must be the confusion.

David Krause
432.368.5483
david@cvaadv.com

**Comment by revsystems** [comment]
Thanks
