### ISSUE TITLE
arrow down icon on top

### ISSUE THREAD

**Issue by logemann** [revsystems/jQuery-SelectBox#25]
HI,

i am using the plugin with latest jQuery 1.5.x and somehow the arrow down icon stays on top of the button. This looks ugly and i dont know how to change this. It seems that the applied style: vertical-allign: middle
has no effect at all. 

I am using Firefox but its the same with Chrome.

Marc

**Comment by revsystems** [comment]
I'll check it out. I haven't done significant testing with jQuery 1.5 yet.

**Comment by logemann** [comment]
i would add a image to further expose this but somehow i dont know how to add images on this tracker....

**Comment by revsystems** [comment]
Easiest way would probably be just to send an email to github@revsystems.com with the image attached. That way I can see what you mean.

By the way, are you using Firefox 3 or 4?

**Comment by logemann** [comment]
another test with image:

---

regards
Marc Logemann
http://www.logemann.org
http://www.logentis.de

Am 30.03.2011 um 15:18 schrieb revsystems:

**Comment by logemann** [comment]
Firefox 3

**Comment by revsystems** [comment]
I know I saw this issue recently when I was re-skinning for a client. I don't think it's related to jQuery-1.5, but rather a CSS oddity. Maybe it's related to inherited font-size or line-height, or something. I ended up ignoring it and just absolutely positioning the arrow. 

Could you put up a quick demo page of the issue so I can debug it? Or even just your css at http://gist.github.com.

**Comment by logemann** [comment]
hmm. gist would be a little bit hard because since i am using jQuery-UI, i have a lot of css files in my HTML. Can you try out your plugin with using a default jQuery-UI css import? It must be jQuery UI because i have disabled all other css files without any change. I cant disable UI because then the whole dialog is not there anymore ;-)

**Comment by revsystems** [comment]
Okay, I was able to duplicate this issue by removing the DOCTYPE from the page, causing it to render in non-standards mode. What is the doctype set to for your page?

**Comment by logemann** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

**Comment by revsystems** [comment]
Yep, verified. The vertical-align works with `<!DOCTYPE html>` (html5) and `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">` (xhtml strict), but fails in transitional mode.

I've pushed a small change to the arrow style in jquery.sb.css that gets around the issue:

  position: absolute;
  top: .5em;
  left: .33em;

Let me know if that fixes it for you.

**Comment by logemann** [comment]
works perfect. Thanks.
