### ISSUE TITLE
Unable to change selected option when using tie

### ISSUE THREAD

**Issue by bcardiff** [revsystems/jQuery-SelectBox#26]
Even in the demo page (example5), if plugin is initialized with useTie option, when trying to change the selected option a JavaScript error is raised.

Uncaught TypeError: Object [object Object] has no method 'old_removeAttr'

SelectBox.selectItemjquery.sb.js:591
SelectBox.clickSBItemjquery.sb.js:617
d.event.handlejquery.min.js:16
d.event.add.m.k.handle.m

I need to remove and add options dynamically in order to creat a cascade selection.

**Comment by revsystems** [comment]
Good catch. I originally coded that into jQuery-SelectBox with the intent to wrap that removeAttr function too--I forgot it in the original tie. Must've missed it the second time around too.

Anyway, I just pushed a new version of tie that wraps removeAttr too. It seems like it fixes it on the demo page to me. Let me know if it's working for you. Thanks
