### ISSUE TITLE
Targeting specific ID

### ISSUE THREAD

**Issue by JayTurn** [revsystems/jQuery-SelectBox#27]
Please forgive me for asking such a noob question but how can we select individual id's? I have tried a number of combinations, including setting up a custom function to getElementById but it doesn't seem to work for me. Is there a built in function for selecting Id's that I am missing?

**Comment by revsystems** [comment]
Not sure what your specific situation is, but I'm assuming you have something like the following markup...

  `<select name="my_name" id="my_id"><option>First option</option><option>Another option</option></select>`

jQuery-SelectBox requires jQuery and operates on jQuery objects. jQuery's syntax to get this specific `<select>` in this situation would be `$("#my_id")`. It uses a css-selector style to pick out elements in the document.

Is that what you're asking about?

**Comment by JayTurn** [comment]
Sorry for the late response revsystems. That is exactly what I was looking for. Thanks very much for the explanation, this is truly an awesome solution. Appreciate the great work you put in to this.
