### ISSUE TITLE
Error when drop down contents contains an '&'

### ISSUE THREAD

**Issue by robertpate** [revsystems/jQuery-SelectBox#28]
If my contents contains an ampersand '&', I get the following error in Firefox 3.6.16:

An invalid or illegal string was specified"  code: "12 http://dev-cfe:9090/resources/jquery/js/jquery-1.5.2.min.js Line 16

Testing in IE9 revealed no errors.  No other browsers where tested.

**Comment by revsystems** [comment]
Is this actually an error that's thrown, or is it a warning thrown by a validator?

Typically you're supposed to escape ampersands that appear directly on the page, e.g. & becomes `&amp;`. if you don't, I think validators will display a warning/error. But I don't know of this causing an issue with behavior. Is this actually breaking the functionality?

**Comment by robertpate** [comment]
It is an error that is thrown on the page and breaks my documents jQuery ready event.  The ampersand is part of the labels in my select box and is escaped when viewed through Firebug, but is not escaped when accessed via the script console and a jQuery select.

**Comment by revsystems** [comment]
I am having trouble reproducing this. I am testing with Firefox 3.6.16 and have set 4 different kinds of ampersand on [the demo page](http://dl.dropbox.com/u/124192/websites/selectbox/index.html), in the "Gift Certificate" test select.

Can you look at that and tell me if I am testing incorrectly?
