### ISSUE TITLE
Dropdown doesn't disappear when clicking on jQuery UI buttons/tabs

### ISSUE THREAD

**Issue by ghost** [revsystems/jQuery-SelectBox#3]
This is actually a bug with jQuery UI that I need to report, and potentially fix. Their event handlers are using return false, which prevents event bubbling. They should be using event.preventDefault().

**Comment by revsystems** [comment]
I've created a pull request for jquery-ui to fix this, so hopefully it will be done in some future release.

**Comment by revsystems** [comment]
My pull request was accepted and landed here:

https://github.com/jquery/jquery-ui/pull/73

So hopefully we'll see it included in jquery UI 1.9.

**Comment by revsystems** [comment]
Closing since no further action will be taken from me on this.
