### ISSUE TITLE
Theme support?

### ISSUE THREAD

**Issue by MV10** [revsystems/jQuery-SelectBox#30]
Have you thought about supporting jQuery UI themes?

I've been looking at various jQuery options for styling select elements for several days now, and I keep coming back to this one for a lot of reasons -- but from a first glance at the CSS, I suspect I'm facing a ton of work to make it visually compatible with our UI theme. Just wondering what your thoughts are about that. Nice work though.

**Comment by revsystems** [comment]
That's a good idea and something I'll look into shortly.

**Comment by MV10** [comment]
Fantastic. You're probably aware of this, but: http://jqueryui.com/docs/Theming/API

I may have some time to look into this myself in the next few days.

**Comment by MV10** [comment]
Cleaning up old stuff.
