### ISSUE TITLE
jQuery 1.6.1 support for serializing forms

### ISSUE THREAD

**Issue by drawain** [revsystems/jQuery-SelectBox#31]
Hi

There is a problem with jQuery 1.6.1: after the select fields changed by the plugin, the jQuery.serialize (.param, etc.) can't see these alterations.

I has to revert jQuery 1.5.1 to make it work.

**Comment by revsystems** [comment]
Yes, I need to work to make this compatible with jQuery-1.6. They changed how attr() works, which affects this plugin quite heavily...

**Comment by revsystems** [comment]
I've pushed a changed that should hopefully fix this. You can see it working with jQuery-1.6.1 on [the demo page](http://dl.dropbox.com/u/124192/websites/selectbox/index.html). If it works for you, it was a simpler change than I thought.

**Comment by drawain** [comment]
Thank you, i'll check tomorrow.
