### ISSUE TITLE
Add Unique Class to $dd Dropdown Markup

### ISSUE THREAD

**Issue by JayTurn** [revsystems/jQuery-SelectBox#32]
I could be going about this the wrong way so please feel free to tell me if that is the case. I am using fixedWidth for a specific selectbox but the select items won't match the width of the selectbox. It is easy enough to target a fixed width for a specific selectbox but the items are not associated with a parent div. They get pulled from the flow and loaded at the end of the `<body>`.

I can't seem to figure out how to provide those items with a specific width value without affecting all selectbox.items which is not what I wish to do. A solution I thought of could be to take the containing div id and pass the name of that to the class in the line below:

`$dd = $("<ul class='" + o.selectboxClass + " items " + $orig.attr("class") + "' role='menu' id='sbdd" + randInt() + "'></ul>")
                .attr("aria-hidden", "true");`

I am just not having any luck accomplishing it. Do you have any ideas on how this could be achieved? Or is there a simple way to do this with CSS that I am missing?

**Comment by revsystems** [comment]
Hi,

The dropdown will have any class on the original select applied to it. So if you have the original `<select class="my_select">...</select>`, the dropdown selectbox markup will be like `<ul class='sb items my_select'>...</ul>`. You can target this new element in css using multiple classes: .sb.items.my_select{...}.

You can have multiple classes on `<select>` elements, so IDs aren't necessary, e.g. `<select class='generic_style specific_select_identifier'>...</select>`.

Does that help?

**Comment by JayTurn** [comment]
Thanks for the fast reply revsystems. I am running this through Drupal which doesn't give direct control over the classes for the `<select>` tag without creating custom form templates. I could add the class to the form template but thought it might be simpler to do it through the above mentioned line.

Is there a simple way to pull the containing div name or am I best off adding the class to the form templates which will then be picked up?

**Comment by revsystems** [comment]
What if you dynamically add some classes to the `<select>` before calling jQuery-SelectBox? Then you don't need to modify the drupal template. For example:

```
<div id='my_special_select_wrapper'>
     <select>...</select>
</div>

$("#my_special_select_wrapper select").addClass("my_special_select");
$("select").sb();
```

Then the `<select>` should set the "my_special_select" class on the dropdown, and you can style from there.

**Comment by JayTurn** [comment]
You are a legend revsystems! That worked perfectly, can't believe I was thinking of such a complex solution and you whip out a nice and simple approach. Thanks a heap!

**Comment by revsystems** [comment]
Great, thanks!
