### ISSUE TITLE
Tabbing into selectbox, changing value then tabbing out loses the new value

### ISSUE THREAD

**Issue by JamesNK** [revsystems/jQuery-SelectBox#35]
When I tab into a selectbox, change its value and then tab out again the selectbox loses its value. Testing using Firefox.

**Comment by behrreich** [comment]
This was a problem for me in that it was not causing the change event for the underlying SELECT to fire.  I found a workaround by simply handling the keypress event on the DIV that is created as follows:

Here is my HTML before sb is called:

```
                    <div class="vehicle-make">
                        <select id="make">
                            <option value="1">(Select Make)</option>
                        </select>
                    </div>
```

Here is my jQuery code to handle the event

```
    jQuery('.vehicle-make:first-child').keypress
    (
        function(e)
        {
            if(e.keyCode == 9)
            {
                make.change();
            }
        }
    );
```

**Comment by ohhaiohhai** [comment]
It seems the value is correct at the end of keydownSB, but no longer correct when stopPageHotkeys runs immediately afterards

**Comment by ohhaiohhai** [comment]
If you don't include the css on the page you can clearly see that the select box is not align with the replacement when using the arrow keys, the value is being set on the select box, I added a lot of debug code- console.log(), but then it "loses it".

I am going to see what happens if I add a new "plugin level variable" named currentValue to store what the value of the select box should be, and see if there is another place I can set the value so it doesnt lose it.

**Comment by behrreich** [comment]
We have experienced various problems with this plug-in when firing 
events based on keystrokes and tabs.  Instead of trying to fix it, we 
are abandoning it for much simpler SELECTs that do not generate heaps of 
HTML for the sake of visual effect like this one does.

Bill

**Comment by ohhaiohhai** [comment]
I found the problem :) Firefox ignore preventDefault() on the keydown event of a select box:

http://stackoverflow.com/questions/6102426/prevent-default-event-for-jquery-keydown-in-firefox

The article, mentions a different problem, but the solution also appears to work for this plugin. It makes it work a bit janky though. My previous comment also fixes the problem, but it is a bit "hackier" I am going to do some testing to see what works better.

**Comment by ohhaiohhai** [comment]
Hackier solution works better, Three changes

1.) Inside SelectBox() I added a new variable called currentValue (for me line number 166):

currentValue = null,

2.) Inside selectItem() I set this value equal to the new value (for me line number 593):

currentValue = newVal;

3.) Inside blurSB() I set the value of the select box equal to current Value (for me line number 772):

$orig.val(currentValue);

With this in place, whenever the select box loses focus, the value is set to whatever was the value to be set to select box. I am sending this solution to our QA team today or tomorrow.

**Comment by Chengyao** [comment]
@eschleeper; I have the same issue. Does your hackier solution work? We have mini version of the plug-in and where do I make the change?

**Comment by ohhaiohhai** [comment]
@Chengyao:

http://pastebin.com/teeEzNyf

**Comment by ohhaiohhai** [comment]
@Chengyao (changes are in the non-minified code in the pastebin ^^)

**Comment by Chengyao** [comment]
Thanks it looks good. Also used YUI compressor to minify it.

> > > eschleeper reply@reply.github.com 6/28/2012 3:52 PM >>>
> > > @Chengyao (changes are in the non-minified code in the pastebin ^^)

---

**Comment by JamesNK** [comment]
Project looks abandoned and I don't use it anymore. Closing.
