### ISSUE TITLE
Visibility issues

### ISSUE THREAD

**Issue by ghola** [revsystems/jQuery-SelectBox#36]
I find that this is the best jquery select styling plugin, yet i can't use it in my application because of small snag, related to visibility.

More precisely, if i have a select that has a CSS style of 'display:none', the plugin will render a visible replacement select, instead of not making any replacement, or making an invisible one.

Another visibility related scenario would be making the original select invisible (using JS), AFTER the replacement selectbox has been generated. The replacement selectbox should become invisible too (should have it's visibility tied to the original select).

These scenarios occur when you have more dynamic forms in which form elements (selects) appear and disappear based on other form elements.

**Comment by ghola** [comment]
One solution to this would be to offer a possibility to select (jquery select by id, class, etc.) the generated selectbox, based on the ID of the original select. This way, i could alter the code that changes the visibility of my original selects to also change the visibility of the generated selects.

Maybe something like storing a reference to the generated selectbox, in the 'data' field (using jquery.data()) of the original select. Or giving the generated selectboxes, an ID that would start (or end) with the ID of the original select.

**Comment by ghola** [comment]
And here's my temporary patch, which adds an 'sbid' attribute to the original select, having as value, the ID of the generated selectbox.

```
// generate new sb ID and assign it to the original select
var id = 'sb' + randInt();
$orig.attr( 'sbid', id );

// create the new sb
$sb = $("<div class='sb " + o.selectboxClass + " " + $orig.attr("class") + "' id='" + id + "'></div>")
```

This is at line 209 of jquery.sb.js

**Comment by MaxPower15** [comment]
The scenario you prevent is a tough one to handle. jQuery-Tie could deal with it, but you'd also need to save the display value so the sb can toggle correctly. Kinda messy.

Rather than do that, I'd recommend just wrapping your select in a `<div>` or a `<span>` with a class/ID you can target. Then both the original `<select>` and sb will be in the same element. Changing the visibility of that container will change both.
