### ISSUE TITLE
ComboBox won't update when jquery-sb is applied

### ISSUE THREAD

**Issue by smsheng** [revsystems/jQuery-SelectBox#4]
Hi,

First of all i would really want to thank you for creating this plugin! Everything works perfectly and i'm able to skin to make it look exactly how i wish it to.

However, i've a issue with combo boxes. For example, my second select box is dependent on the value of the first chosen, when jquery-sb is applied, the value of the second box no longer updates dynamically. 

Any idea how i can go abt solving that? thanks!

**Comment by MaxPower15** [comment]
Hi,

It's in the demo/example code, but isn't really documented well enough--you can use $("select").triggerHandler("reload"), then that will effectively destroy/rebuild the selectbox, applying any changes you've made to the underlying select.

For your case, I'm assuming you have a function that (a) removes the options of your dynamic select, then (b) goes through a loop to add options based on your first select. After this loop, you should be able to use $("special-selector").triggerHandler("reload"); where $("special-selector") is your dynamic select element.

If you look in main.js here, you'll see I do this in the demo.

Hope that helps.

**Comment by smsheng** [comment]
Hi thanks for your reply!

I'm using cakephp and i'm using the ajax observefield function to update options of the second select list when there's a change in the selection of the first.

i guess the observefield function is not triggered when i use the jQuery-SelectBox plugin since it's not detecting a change in the selection of the first selectionbox?

I'm all new to all these and i guess you won't be knowing what i'm talking abt if you're not familiar with cakephp.

I'll try to figure out. thanks a lot anyway!

**Comment by MaxPower15** [comment]
It should detect a change in the first selectbox (the "change" event is triggered on the old select element when you use jquery-sb). It is likely updating the select element behind the scenes, but the new markup doesn't reflect that because it doesn't know to reload. I would try to confirm this by looking at the markup in Firebug.

It is possible to create a hack that monitors dom changes in the select and calls reload when it detects a change. (We'd probably set up a timeout in this case so it only reloads once instead of 100 times or so.) I created another plugin that can handle the monitoring, jquery.tie.js, but I can't release it just yet. I'll check how long it will be.

Hope you can get something working in the meantime.

**Comment by smsheng** [comment]
thanks alot! you're right. The select elements are being updated but it just not reflected in the second selectbox.

Meantime, i'll try to work something out and hope you'll release the new plugin soon when it's ready!

thanks

**Comment by smsheng** [comment]
sorry to bother again. I need some pointers, hope you don't mind. 

I've managed to do what you suggested. I've used the "change" event to detect changes in the first selectbox and tried to call "reload"

```
<script type="text/javascript" charset="utf-8">
     $(document).ready(function() {
      $("select").sb();      
        $('#selectbox1').change(function() {
          $('#selectbox2').trigger("reload");
        });             
    });     
</script>  
```

When you first make a selection in selectbox1, selectbox2 does not update. However, when you try to select a value again from selectbox1, selectbox2 updates with the values from the option you first selected instead of the current selection from selectbox1.

For example, if you were to choose option1 in selectbox1, you're expected to get values1 in selectbox2 but nothing happens. However, if you were to select option2 in selectbox1 again, you'll get values1 instead of values2. Selectbox2 always updates with the values from the previous selection.

any ideas?

**Comment by MaxPower15** [comment]
I think you're running into an issue with asynchronous calls. You're using ajax, so it takes some arbitrary amount of time for your site to return with the data for selectbox2. Your change function does not need to wait for the server, so it is executed immediately--when it is executed, the values of selectbox1 are still there.

Ideally, you want to find the function that is called when the ajax data is returned, and add the reload trigger there.

You could also do some polling tricks with setTimeout, but you should avoid it if at all possible. You'll be better off if you can find the right function to add the reload trigger.

**Comment by smsheng** [comment]
you're right! Thanks alot!! I truly appreciate your help!

**Comment by MaxPower15** [comment]
No problem, hope you can get it working. : )

**Comment by revsystems** [comment]
Hi smsheng,

In case you're interested, I've pushed the other plugin I was talking about, called [jquery.tie](https://github.com/revsystems/jQuery-Tie), to github along with a new version of jquery-sb that's already integrated with it.

You can check it out on the demo page and its usage is now in the Readme. Just look for the "useTie" option.

**Comment by smsheng** [comment]
thanks a lot! i'll check it out!

**Comment by smsheng** [comment]
thanks for the jtie plugin but i've running into some problems and it's entirely down to my unfamiliarity with javascripts and jquery.

can you pls show me how to implement the following using the new jtie script?

<script type="text/javascript" charset="utf-8">
     $(document).ready(function() {
      $("select").sb();      
        $('#selectbox1').change(function() {
          $('#selectbox2').trigger("reload");
        });             
    });     
</script> 


how to i make it reload another div instead of just reloading itself?

  $("#selectbox1").sb({ useTie: true });
  $("#selectbox1").trigger("reload");

**Comment by smsheng** [comment]
HeyHey!

My bad! Everything just works out of the box! Sorry i was just abit confused! 
Everything's working as it was supposed to !

thanks again!
