### ISSUE TITLE
SelectBox doesn't seem to support the select attribute 'multiple'.

### ISSUE THREAD

**Issue by n3nn00** [revsystems/jQuery-SelectBox#42]
I've read over the documentation and am unable to find a reference to 'multiple' and when I have a <select multiple='multiple'> and then launch the selectBox plugin, the multipleness of the select is ignored.  Is there a way to enable 'multiple' or are there plans to add support for 'multiple'?

**Comment by MaxPower15** [comment]
Multiple is not currently supported and there are no plans to support it. Programmatically, it's just a totally different kind of control from a standard select, so it's not easy to shoehorn in support. Sorry, I wish it were easier.

**Comment by n3nn00** [comment]
Thanks for the quick response.  If I'm able to come up with anything I'll let you guys know.
