### ISSUE TITLE
Fixed width styling is unclear

### ISSUE THREAD

**Issue by ghost** [revsystems/jQuery-SelectBox#7]
Need to make it clear and easy how to make the selectbox and dropdown a fixed width.

**Comment by tvdeyen** [comment]
Yeah, this is not clear :)

I set fixedWidth to true and the ul.items does not have the width of the widest value. Or am I missing something? Setting it to false does not change anything.

**Comment by revsystems** [comment]
Currently the way to set the fixed width is use the fixedWidth: false option, then specify a width on .selectbox .display in the css. Definitely need a better way to do it... shouldn't be too long.

**Comment by revsystems** [comment]
I added a fixed width example to the demo page, and info on it in the Readme. I think the current solution allows the best balance of dynamic sizing and stylability.
