### ISSUE TITLE
Not changing value if the original select changes value

### ISSUE THREAD

**Issue by tvdeyen** [revsystems/jQuery-SelectBox#9]
If change the value of the original select element via jQuery('#my_select').value('foo') then the sb selectbox does not change value.

**Comment by revsystems** [comment]
If you have control over when the original select is updated programatically, you should use jQuery("#my_select").value('foo').triggerHandler("reload"). This will force the sb selectbox to reload. If you view the source on the demo page, I demonstrate that there.

If you do NOT have control over the updating js (maybe when working in a framework), jQuery-Tie (another plugin I wrote) can be used with jQuery-SelectBox to automatically update the sb selectbox. For info on this, look for the "useTie" option in the readme.

**Comment by tvdeyen** [comment]
Ah, ok. Thanks. I have the control, so no problem.
